# Generated by Django 5.2.1 on 2025-06-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(blank=True, help_text='이 노드가 QR코드 위치일 경우, QR코드에 저장될 고유 ID', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='노드의 이름 또는 설명 (예: 1층 정문 앞 QR)', max_length=100)),
                ('floor', models.CharField(help_text='층 정보 (예: 1F, B1)', max_length=10)),
                ('pixel_x', models.IntegerField(help_text='PNG 이미지 상의 X 좌표 (픽셀)')),
                ('pixel_y', models.IntegerField(help_text='PNG 이미지 상의 Y 좌표 (픽셀)')),
                ('node_type', models.CharField(choices=[('QR', 'QR Code Spot'), ('JUNCTION', 'Junction'), ('POI', 'Point of Interest'), ('ELEVATOR', 'Elevator'), ('STAIRS', 'Stairs'), ('ETC', 'Etc')], default='ETC', help_text='노드 유형', max_length=20)),
                ('description', models.TextField(blank=True, help_text='노드에 대한 추가 설명', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='가중치 (보통 노드 간의 픽셀 거리를 저장)')),
                ('end_node', models.ForeignKey(help_text='도착 노드', on_delete=django.db.models.deletion.CASCADE, related_name='ending_edges', to='navigation.node')),
                ('start_node', models.ForeignKey(help_text='시작 노드', on_delete=django.db.models.deletion.CASCADE, related_name='starting_edges', to='navigation.node')),
            ],
        ),
    ]
