# Generated by Django 5.2.1 on 2025-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='building',
            field=models.CharField(help_text='건물 이름', max_length=100, null=True),
        ),
    ]
